version: '3.5' # docker-compose version

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - stagingnetwork
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
