# 當前用不到，未來可能會用先留著

version: '3.5' # docker-compose version

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
